### ISSUE TITLE
Energy summation not correct?

### ISSUE THREAD

**Issue by dr-ni** [jeanmarc77/123solar#13]
I have some problems with the energy count. It is counting too much. Is your curve smoothing algorithm working correct?

![slog](https://user-images.githubusercontent.com/68241100/166676462-06728a7e-cea6-451b-aea3-8226d82a80ca.png)

Here my log:
[slog.txt](https://github.com/jeanmarc77/123solar/files/8620106/slog.txt)

**Comment by jeanmarc77** [comment]
Sure, the avg power is calculated between 2 samples with a second precision

**Comment by dr-ni** [comment]
I've found the main problem:
https://github.com/jeanmarc77/123solar/pull/14

but still I get different curves with two 123solar running paralel

**Comment by dr-ni** [comment]
Another question:
Why is the power-meter on the main page often going up to Pnow and down to 0 - even if continuous power is feeded?

**Comment by jeanmarc77** [comment]
It mean your app return 0 or your last live sample is 30sec too old.
Please don't use issue for help/question but only for issue/improvement
