### ISSUE TITLE
logger stopped with this error

### ISSUE THREAD

**Issue by M0stie** [jeanmarc77/123solar#17]
PHP Fatal error: Uncaught ValueError: fread(): Argument #2 ($length) must be greater than 0 in /srv/http/123solar/scripts/123solar.php:650
Stack trace:
#0 /srv/http/123solar/scripts/123solar.php(650): fread()
#1 {main}
thrown in /srv/http/123solar/scripts/123solar.php on line 650

Its been running since Janaury with no issues and nothing has been updated, it just stopped on Saturday

**Comment by jeanmarc77** [comment]
Hi,
Never had that issue, but it is fixed in main branch
https://github.com/jeanmarc77/123solar/commit/94e54d649fe6491eb1c2c38f3e05f61e6501eb5c

**Comment by M0stie** [comment]
Thank you, it’s been working now for a couple of days 

Graham

**Comment by jeanmarc77** [comment]
I understand, it's because you use a GIT clone, instead of using the stable release
