### ISSUE TITLE
git clone

### ISSUE THREAD

**Issue by halfagascan** [jeanmarc77/123solar#2]
git clone of this missing files.
missing some /24 images sign-check for one
didn't have the start stop button
configs would not save
download from your website works, web pages load with errors:
[error] 640#640: *4 FastCGI sent in stderr: "PHP message: PHP Warning:  chmod():
still troubleshooting
thanks

**Comment by halfagascan** [comment]
download from the website = good operating system, some errors
download from github = many errors,missing files, icons, etc
clean install on debian bullseye and fresh archarm install

**Comment by jeanmarc77** [comment]
i work on it
