### ISSUE TITLE
PHP8.0 Compatibility

### ISSUE THREAD

**Issue by escix** [jeanmarc77/123solar#22]
Hi,
Is this code compatible with PHP8.0.
I am getting lots of error with PHP8.0 where is was working fine with PHP7.2

**Comment by jeanmarc77** [comment]
Sure, i run with PHP 8.1.8.
What are the error ? Check hints into '[Help and debugger]'

**Comment by escix** [comment]
the script doesn't create the 123solar.pid file.
Also I had the following errors:
PHP Warning:  Trying to access array offset on value of type null in...

Checking running softwares is also blank.

**Comment by jeanmarc77** [comment]
What about admin/fperms.php ?

**Comment by escix** [comment]
All OK

**Comment by jeanmarc77** [comment]
duh.. maybe enable debug, restart 123s, check also your webserver error log and send me more details

**Comment by escix** [comment]
I run 123Solar in FreeBSD, which I run before too but older version in Raspberry PI.
Now moved to x64 thinclient and upgraded to latest version with PHP8.0.
The reading works still, but the button in the admin panel stays off.

**Comment by jeanmarc77** [comment]
do you have a ../scripts/123solar.pid file ? I guess not, that's the issue

**Comment by escix** [comment]
Now fixed the ps command in admin/help.php file for FreeBSD.
Now the Running Softwares in the help.php shows the running processes.

The 123solar.pid file is not getting created when starting. not sure why?

**Comment by jeanmarc77** [comment]
maybe the command is unappropriate for FreeBSD, in admin line 118 : ps -ef | grep $PID | grep 123solar.php

**Comment by escix** [comment]
perfect, working now.
Cheers

**Comment by jeanmarc77** [comment]
what was the command ? 

i guess scripts/distros/ commands are not good for FreeBSD. Mind checking them and make a new one ?
I could set the PID command return different by setting distro in admin panel.

**Comment by escix** [comment]
ps -auxw to display all processes

**Comment by jeanmarc77** [comment]
ok and what for 
$UPTIME=
$CPUUSE=
$MEMTOT=
$MEMUSE=
$MEMFREE=
$DISKUSE=
$DISKFREE

**Comment by escix** [comment]
Except $MEM* everything else works as expected.
For memory info a pkg needs to beinstalled. I think it is memfree or freemem or similar. Sorry I forgot - which I don't have installed.

**Comment by jeanmarc77** [comment]
ok, so tell me if you know. I work by implementing PID via distro
thanks

**Comment by escix** [comment]
Could you use something like this:

sysctl -a | grep 'real memory'
sysctl -a | grep 'avail memory'

**Comment by jeanmarc77** [comment]
i've push on git, it will work on next stable update.
Mind checking https://github.com/jeanmarc77/123solar/blob/main/scripts/distros/FreeBSD.php ?

**Comment by escix** [comment]
$CPUUSE="ps aux|awk 'NR > 0 { s +=$3 }; END {print \"cpu %\",s}' | awk '{ print $3 }'";

this doesn't work

error:
awk: syntax error at source line 1
 context is
        NR > 0 { s +=$3 }; END {print >>>  \ <<< "cpu %\",s}
awk: illegal statement at source line 1

**Comment by jeanmarc77** [comment]
please provide the full working FreeBSD.php, i'll push it on git

**Comment by escix** [comment]
$CPUUSE="ps aux | awk 'NR > 2 { s +=$3 }; END {print "cpu %",s}' | awk '{print $3 }'"

**Comment by escix** [comment]
How does the distro files work?
Does it automatically get the info or does it need to be modified in each php files?

for eg. in info.php there is this command which won't work in FreeBSD:
cat /proc/cpuinfo | grep 'Processor' | head -n 1

same in admin.php as stated before.

**Comment by jeanmarc77** [comment]
Not all commands are define there like cpuinfo, i can add them via distros files.
It simply PHP exec the commands, just tell me what's work on BSD.

I've modify admin.php https://github.com/jeanmarc77/123solar/blob/main/admin/admin.php

**Comment by escix** [comment]
$CPUUSE="ps aux | awk 'NR > 0 { s +=$3 }; END {print "\cpu %",s}' | awk '{ print $3 }'";

When I use the above command i get the following error:
FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected fully qualified name "\cpu" in

But it works on command line if I execute as user www.


% ps aux | awk 'NR > 0 { s +=$3 }; END {print "cpu %",s}' | awk '{ print $3 }'
0
%

**Comment by jeanmarc77** [comment]
You miss a \, that's
$CPUUSE="ps aux | awk 'NR > 0 { s +=$3 }; END {print "\cpu %\",s}' | awk '{ print $3 }'";

**Comment by escix** [comment]
I am getting an error when I put that backslash.

What should be the output from the above command?
Is that just a number or cpu % 10 ?

**Comment by jeanmarc77** [comment]
It should return a value like 25 which mean 25%

don't forget to remove the escape backslash if in CLI
`ps aux|awk 'NR > 0 { s +=$3 }; END {print "cpu %",s}' | awk '{ print $3 }'`

**Comment by escix** [comment]
the one in the Ubuntu works.

Does it only shows the cpuuse for 123solar or for all processes?

**Comment by escix** [comment]
> 

That's it I was checking in the CLI and not working, but it was working in the web

**Comment by jeanmarc77** [comment]
It's total CPU usage like you can see via top.

CPU/men usage of 123s is seen on help page, lines 47 & 48
`	$cpu = exec("ps -p $PID -o %cpu | tail -1 | awk '{print $1}'");
	$mem = exec("ps -p $PID -o %mem | tail -1 | awk '{print $1}'");
`

**Comment by escix** [comment]
yes you are correct. It is the cpuuse by www user.

**Comment by jeanmarc77** [comment]
Maybe this 
`
$loads = sys_getloadavg();
$core_nums = trim(shell_exec("grep -P '^processor' /proc/cpuinfo|wc -l"));
$CPUUSE = round($loads[0]/($core_nums + 1)*100, 2);

`
