### ISSUE TITLE
changing meter size when current is higher than 10A

### ISSUE THREAD

**Issue by dr-ni** [jeanmarc77/123solar#27]
if the resolution is <= 720p the meter size is always changin because of an unwanted linebreak

possible fix: change VDC to V to save space

**Comment by jeanmarc77** [comment]
Hi,
I believe it's wiser to keep VDC, as people can mess up with array and grid voltage.
It can change it to ⎓ light be cooler.
Nobody use <720p ;)

**Comment by dr-ni** [comment]
ok keep me informed so I can test it

**Comment by jeanmarc77** [comment]
ok you can give it a try, even though 123s interface is suppose to be see on a pc monitor.
There is m.php, which is supposed to be mobile or minimale interface. (i haven't work on it much)

**Comment by dr-ni** [comment]
perfect :-)
