### ISSUE TITLE
PHP Fatal error:  Uncaught ValueError

### ISSUE THREAD

**Issue by kitenski** [jeanmarc77/123solar#35]
I noticed my long running 123solar wasn't up, everytime I restarted it, it died quickly.

Turning on debug shows the following:

#* 31/10/2022 12:03:08	Starting 123Solar debug (1461)

PHP Fatal error:  Uncaught ValueError: fread(): Argument #2 ($length) must be greater than 0 in /srv/http/123solar/scripts/123solar.php:650
Stack trace:
#0 /srv/http/123solar/scripts/123solar.php(650): fread()
#1 {main}
  thrown in /srv/http/123solar/scripts/123solar.php on line 650

**Comment by jeanmarc77** [comment]
Hi,
You probably have a empty file in data/invtX/msgqueue/, try to remove it

**Comment by kitenski** [comment]
thanks, indeed, that has fixed it!

There were many empty files!

1666767540R.txt  1667215800R.txt  1667217180R.txt  1667218200R.txt

1666872840R.txt  1667216220R.txt  1667217720R.txt  1667218380R.txt

1667213940R.txt  1667216340R.txt  1667217780R.txt

**Comment by kitenski** [comment]
UK autumn at it's finest, or old panels maybe?

<img width="753" alt="image" src="https://user-images.githubusercontent.com/302805/199017311-eae685fc-ab37-4ab3-8a0e-3c159550adc5.png">

**Comment by jeanmarc77** [comment]
A low Riso can happen because of a poor ground (too dry) and, ileak when it's stormy weather, i think it's because of static electricity.
Anyway, your message files shouldn't have to be empty, maybe your logger was writing when you shut it down or a SDcard that is slowly dying
