### ISSUE TITLE
is 123solar-website forced to port 80 ?

### ISSUE THREAD

**Issue by emka70** [jeanmarc77/123solar#36]
Hi Jeanmarc,
I tried to change my 123solar-http-site from port 80 to port 123 via apache2's ports.conf/123solar.conf/000-default.conf, but I won't get it working.

Before searching at the wrong side:
are there some limitations from 123solar that force the webserver to use port 80 ?

thanx for your great work !
best wishes
Michael

**Comment by jeanmarc77** [comment]
Hi,
123s or whatever http service can run on any port. It's only related to your server configuration.
Bye
