### ISSUE TITLE
how can I stop sunset auto on/off and log 24 hours?

### ISSUE THREAD

**Issue by dr-ni** [jeanmarc77/123solar#39]
- which files do I have to change?

**Comment by jeanmarc77** [comment]
why do you want to change that ?

**Comment by dr-ni** [comment]
I'm running also a windgenerator which is working also at night

**Comment by jeanmarc77** [comment]
neat but 123s is intended for solar inverters. Maybe meterN will fit your need or you may tweak the code.

**Comment by dr-ni** [comment]
I don't want to use meterN. I just want to tweak 123s. So a small hint where the auto on/off is in the code would be very helpfull

**Comment by jeanmarc77** [comment]
Set $memarray['awake'] to true but that will lead to 'communication error' and 'Missing 5' sample' for your solar inverter

**Comment by dr-ni** [comment]
ok I'll try, thank you :-)
