### ISSUE TITLE
Feature request: automatic startup

### ISSUE THREAD

**Issue by R1ckj** [jeanmarc77/123solar#40]
Would it be possible to have an option to automatically startup 123solar? I know there is a script but in my setup it is not working (I have 123solar running in a docker container and nginx web server running in another container). I would like to avoid adding a cron script at every startup to start 123solar.

**Comment by jeanmarc77** [comment]
Hi,
I don't know how docker works but i think you can run a bash script that makes a curl request to boot123s.php

**Comment by jeanmarc77** [comment]
Maybe it's wiser to ask to https://github.com/EdoFede/123Solar-meterN-Docker

**Comment by jeanmarc77** [comment]
unrelated to 123s
