### ISSUE TITLE
wrong yAxis Maximum for multiple inverters 

### ISSUE THREAD

**Issue by dr-ni** [jeanmarc77/123solar#43]
Settings:
Inverter 1: yAxis Maximum 600 W
Inverter 2: yAxis Maximum 600 W

Index page yAxis Maximum is 1200 W but should be 600 W because logging curves never reach more than 600 W

**Comment by jeanmarc77** [comment]
depend on your config, most have several invt production that accumulate.
you can set yAxis Maximum to 300 if you prefer

**Comment by dr-ni** [comment]
if I'll set it to 300 then the single pages inv1 and inv2 will be also 300 but should be 600

**Comment by jeanmarc77** [comment]
If i change i guess most people will complain. Do you have a proposition ?
Meanwill you can change 
yAxis: {
        max: null
    }

**Comment by dr-ni** [comment]
maybe you can add an additional yAxis Maximum setting for the Index page?
