### ISSUE TITLE
Last 20 Days Changed

### ISSUE THREAD

**Issue by halfagascan** [jeanmarc77/123solar#46]
Something changed with viewing the last 20 days graph, yesterday it was the normal vertical bars, today its a line graph.
![123solar1](https://user-images.githubusercontent.com/43622819/234583442-2510edce-9faa-43ad-b5ca-fd7dd4cd2af8.png)

**Comment by jeanmarc77** [comment]
Yup see https://github.com/jeanmarc77/meterN/issues/10

**Comment by halfagascan** [comment]
Installed new index.php
restart nginx, php-fpm7.4
The dashboard gauge went goofy
Installed php-fpm8.2
start php8.2
guage returns, the last 20 days, no change, still shows a line graph
systemctl stop php-fpm7.4
Results in bad gateway
systemctl start php-fpm7.4 works, but line graph is there, with both php-fpm8.2 and php-fpm7.4 running

php -v
PHP 8.2.5 (cli) (built: Apr 14 2023 04:39:46) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.5, Copyright (c), by Zend Technologi

**Comment by jeanmarc77** [comment]
what version does it show on your browser ? https://code.highcharts.com/highcharts.js and https://code.highcharts.com/highcharts-more.js
You sure you use latest index.php ? I have no glitches

**Comment by halfagascan** [comment]
Highcharts JS v10.3.3 (2023-01-20)

 Highcharts JS v11.0.0 (2023-04-26)
copied the index.php from your metern link issue

**Comment by jeanmarc77** [comment]
It should show Highcharts V11.. force that damn resfresh :p
Also use index for 123s https://github.com/jeanmarc77/123solar/blob/main/index.php

**Comment by halfagascan** [comment]
Not sure what the hell is going on.
Started looking for a howto force update Highcharts, my duck foo is not working.
Both of the links to check the version now show Highcharts JS v11.0.0 (2023-04-26)
Still have the line graph.
thanks

**Comment by jeanmarc77** [comment]
and you sure you took the latest https://github.com/jeanmarc77/123solar/blob/main/index.php ?

**Comment by jeanmarc77** [comment]
You have several inverters ?

**Comment by halfagascan** [comment]
Just one

**Comment by halfagascan** [comment]
here a screen from android brave browser
![123solar_Brave](https://user-images.githubusercontent.com/43622819/234676510-323f2497-6aa5-4e1c-9366-518ec31334e8.png)

**Comment by halfagascan** [comment]
to add
win10 firefox 112.0.1 line graph shows, dash gauge is good
win 10 microsoft edge 112.0.1722.58  dash gauge shows lines, last 20 days good

**Comment by soe135** [comment]
For the last two days I've been having the same damn problem with the distorted dashboard display as halfagascan. The problem occurs with all different browsers that I use (Firefox, Chrome, Edge), regardless of the operating system (Windows, Linux or Android). The problem seems to start synchronously with the new version of highcharts.js (Highcharts JS v11.0.0 (2023-04-26)).  Any suggestions on how to fix the problem?

**Comment by halfagascan** [comment]
So, is this an upstream bug with highcharts.js? if so can you link the report?

**Comment by jeanmarc77** [comment]
@halfagascan There is not issue with highcharts. 
did you use latest index (on git) and clear the cache ?

**Comment by halfagascan** [comment]
solved thanks
