### ISSUE TITLE
the display of the last 20 days has changed

### ISSUE THREAD

**Issue by obduser** [jeanmarc77/123solar#47]
Without changing the installation of 123solar (V1.8.4.1 is installed), the display of the last 20 days has changed to a line graphic 
! How can this happen ?

![Unbenannt](https://github.com/jeanmarc77/123solar/assets/28684534/920591ae-b64c-4faf-8ac4-f59fd90803a4)

**Comment by jeanmarc77** [comment]
Use the latest release before submit bug and read previous closed ones
