### ISSUE TITLE
not update from web

### ISSUE THREAD

**Issue by wifi75** [jeanmarc77/123solar#6]
Hello after update I have this error, why?

![image](https://user-images.githubusercontent.com/31816231/148676966-10264c2c-bead-449c-9ef9-15e4d12b7dcc.png)

**Comment by jeanmarc77** [comment]
Hi,
You need to use 1.8.4.4 to allow updt via github. You have to [manually update](https://github.com/jeanmarc77/123solar/wiki/Help#how-to-update-)

**Comment by jeanmarc77** [comment]
I have update. It will allow update from older version will the 123solar.org domain work
