### ISSUE TITLE
Peak power and Ileak in dasboard page

### ISSUE THREAD

**Issue by guadax** [jeanmarc77/123solar#61]
Cannot say if it is a real issue but on the dashboard page there are values that remain zero
Using 123solar on raspberry pi zero w  with sbfspot 3.9.7 working great.

Values are ileak  and peak power. Ok for ileak (sunny explorer says 5ma) but what about peak power?

What is temperature booster (alias booster temperatura in italian)? What it means?

![image](https://github.com/jeanmarc77/123solar/assets/66492267/f42fae5d-a904-43fe-91d4-b7a363a8b94c)

Same value in the main page is ok 

![image](https://github.com/jeanmarc77/123solar/assets/66492267/e24548e0-47b0-4e50-9e5b-4b2fffb8d316)

**Comment by jeanmarc77** [comment]
Hi,
ileak is not reported by sma. Also read the wiki about peak power
https://github.com/jeanmarc77/123solar/wiki/2)-Help
