### ISSUE TITLE
2024 not being populated

### ISSUE THREAD

**Issue by maurizioandreotti** [jeanmarc77/123solar#70]
since the beginning of the year the system, although it reads data from the inverter:

![image](https://github.com/jeanmarc77/123solar/assets/7696314/8889dc11-3d6c-4a8a-9395-ab2b16c4f995)

it seems not showing nor storing the data correctly:
![image](https://github.com/jeanmarc77/123solar/assets/7696314/eab83606-f054-4ae7-bbb9-0697f42c5c5f)

![image](https://github.com/jeanmarc77/123solar/assets/7696314/377df6bb-04f2-4992-9884-ae65fb1614aa)

 it's not populating the 2024 data.

![image](https://github.com/jeanmarc77/123solar/assets/7696314/43de8499-9977-40b1-9e9f-4c65be9c13e5)

I tried downloading a fresh version from github and reinstall, but howthing changed.

what shall i do?

**Comment by jeanmarc77** [comment]
Hi,
github code is work in progress, you need to releases https://github.com/jeanmarc77/123solar/releases
Check Files permissions 123solar/admin/fperms.php

**Comment by maurizioandreotti** [comment]
![image](https://github.com/jeanmarc77/123solar/assets/7696314/3d6e11c2-6b4f-4185-b66e-ab29f624005d)

**Comment by jeanmarc77** [comment]
Weird.. check your webserver error log

**Comment by maurizioandreotti** [comment]
thanks.

i see no issues shown in any of the log (ngnix, php etc). but trying to copy the 123solar data folder i am now getting read errors..... so i think i got disk issue,

will see to reinstall the raspberry

**Comment by maurizioandreotti** [comment]
I checked and info page say that i am running 123Solar 1.8.4.5

in file 123solar.err i see thousands of these notices:
PHP Warning:  include(../config/pvoutput/consumption/.php): failed to open stream: No such file or directory in /var/www/html/123solar/scripts/123solar.php on line 459
PHP Warning:  include(): Failed opening '../config/pvoutput/consumption/.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/123solar/scripts/123solar.php on line 459
PHP Notice:  Undefined variable: PVOT1 in /var/www/html/123solar/scripts/123solar.php on line 461
PHP Notice:  Undefined variable: PVOT1 in /var/www/html/123solar/scripts/123solar.php on line 462
PHP Warning:  include(../config/pvoutput/temperature/.php): failed to open stream: No such file or directory in /var/www/html/123solar/scripts/123solar.php on line 462
PHP Warning:  include(): Failed opening '../config/pvoutput/temperature/.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/123solar/scripts/123solar.php on line 462
PHP Notice:  Undefined variable: APIKEY1 in /var/www/html/123solar/scripts/123solar.php on line 470
PHP Notice:  Undefined variable: SYSID1 in /var/www/html/123solar/scripts/123solar.php on line 471
PHP Notice:  Undefined variable: PVOEXT1 in /var/www/html/123solar/scripts/123solar.php on line 480
PHP Notice:  Undefined variable: SYSID1 in /var/www/html/123solar/scripts/123solar.php on line 490
PHP Notice:  Undefined variable: PVOEXT1 in /var/www/html/123solar/scripts/123solar.php on line 491
PHP Notice:  Undefined variable: PVOUTPUT11 in /var/www/html/123solar/scripts/123solar.php on line 397
PHP Notice:  Undefined variable: PVOT1 in /var/www/html/123solar/scripts/123solar.php on line 451
PHP Notice:  Undefined variable: PVOC1 in /var/www/html/123solar/scripts/123solar.php on line 458
PHP Notice:  Undefined variable: PVOC1 in /var/www/html/123solar/scripts/123solar.php on line 459

**Comment by jeanmarc77** [comment]
Did you set "Consumption" 123solar/admin/admin_pvo.php ?
What show config/config_pvoutput.php ? (obfuscate values!)

**Comment by maurizioandreotti** [comment]
no, it was always set to no:

![image](https://github.com/jeanmarc77/123solar/assets/7696314/ad8a17a6-7e6b-434b-9206-6d811e021a92)

**Comment by jeanmarc77** [comment]
and the content of config/config_pvoutput.php ?

**Comment by maurizioandreotti** [comment]
maurizio@aurora:/var/www/html/123solar $ more config/config_pvoutput.php
<?php
if(!defined('checkaccess')){die('Direct access not permitted');}

// ### PVOUTPUT.org
$NUMPVO=0;

$SYSID1='0';
$APIKEY1='';
$PVOC1='no';
$PVOT1='inverter';
$PVOEXT1=false;
$PVOUTPUT11=false;

$cfgver=1451373026;
?>

**Comment by jeanmarc77** [comment]
it's empty, so save PVoutput cfg

**Comment by maurizioandreotti** [comment]
anyhow my problem is tghat it soedn create the 2024 csv.

yesterday i was ssindg daily watts, and 2024 in the historic window, but then when the day changed it went badk to show only 2023.

![image](https://github.com/jeanmarc77/123solar/assets/7696314/ff826725-7bbf-465f-946d-9444335e0cd2)

**Comment by jeanmarc77** [comment]
Live values are ephemerous and they are not recorded in csv files. Hence why i suppose it's a permission issue or maybe a faulty/full drive

**Comment by maurizioandreotti** [comment]
Hi Juean,
it was a faulty SD card in the raspberry: at some point in time it deceided to be only readonly, so the raspy was booting adn working, but not saving any file at all.

I had around another one which turned out to be faulty (this time showing random /w errors), so i  had to get a brand new one. and reinstall everything from scratch.

at this point in time it seems working fine since ithe last 2 days, 

 I have 2024 data (well yes, i had to donwload the hisory from the aruora inveerter and setup the 2024.csv file for the past months)

the only strange thing which is see is that the "last 20 days" graph shows a production of 0,

![image](https://github.com/jeanmarc77/123solar/assets/7696314/11da6185-27d7-4f27-ac77-1814727b0ceb)

 while, if I click on it i can see the graph of the last day (as weel as the day before, going further back i cannot see, but that is expected as the systsem was being reinstalled):
![image](https://github.com/jeanmarc77/123solar/assets/7696314/a900762c-aeef-41c4-94cc-05e27b295670)

**Comment by jeanmarc77** [comment]
great, you'll get previous days next
