### ISSUE TITLE
Question - different peak values in different pages

### ISSUE THREAD

**Issue by maurizioandreotti** [jeanmarc77/123solar#71]
Hi!. I am courious to understand why i see a peak value on the home page from the one into the dashboard:

![image](https://github.com/jeanmarc77/123solar/assets/7696314/4563a1dc-81b1-4e17-8db2-cafdd322945c)

![image](https://github.com/jeanmarc77/123solar/assets/7696314/2344a2e0-77cd-4214-97f3-6d8cbac81698)

is it because the dashboard one is got by the 123solar in its 5min measures of the day and the other one in the home page is the peak of peaks it has measured ?

also i don't see the same "peak" value in the graphs:
![image](https://github.com/jeanmarc77/123solar/assets/7696314/20be481e-7c92-47bb-a682-5c0452cfdee4)

**Comment by jeanmarc77** [comment]
Hi,
Read the wiki

https://github.com/jeanmarc77/123solar/wiki/2)-Help#why-the-max-instantaneous-power-value-on-the-main-page-arent-the-same-than-the-power-peak-in-the-dashboard-

https://github.com/jeanmarc77/123solar/wiki/2)-Help#why-the-top-value-on-the-main-daily-graph-is-different-than-max-instantaneous-power-and-power-peak-in-the-dashboard-

**Comment by maurizioandreotti** [comment]
thanks

Il giorno ven 17 mag 2024 alle ore 14:11 Jean-Marc Louviaux <
***@***.***> ha scritto:
