### ISSUE TITLE
Fronius script adaption

### ISSUE THREAD

**Issue by riogrande75** [jeanmarc77/123solar#78]
Because of a slight api change in fornius' datamanager, the link for pooling in script fronius.php has to be adapted.
DeviceI**D** must be changed to DeviceI**d**

`curl_setopt($ch, CURLOPT_URL, "http://${'ADR'.$invt_num}/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=CommonInverterData");`

Pls. see also:
[Fronius API Device ID](https://forum.pvoutput.org/t/fronius-api-device-id/5025)

**Comment by jeanmarc77** [comment]
fixed
