### ISSUE TITLE
123solar freezing taking readings, but web and admin interfaces available

### ISSUE THREAD

**Issue by kitenski** [jeanmarc77/123solar#9]
I've had about 4 instances in the past month where 123solar doesn't appear to be receiving any data. I notice as the previous days readings are missing and the live guage is on zero when there is sun outside!

When it was frozen an hour ago I tried the enhanced comms tester which said it wasn't connected.

I rebooted the Raspberry PI and it started working fine again. Toggling 123solar on/off from the admin doesn't work.

I wonder if a Linux update is having the USB port drop out or power off to save energy (complete guess at my end?)

**Comment by jeanmarc77** [comment]
Please it's not an issue with 123s don't use this for help
Maybe your converter is dying or on your system configuration
